from src.data import INPUT_TAG, CONTEXT_TAG

dataset2prompt = {
    "hotpotqa": f"Answer the question based on the given passages. Only give me the answer and do not output any other words.\n\nThe following are given passages.\n{CONTEXT_TAG}\n\nAnswer the question based on the given passages. Only give me the answer and do not output any other words.\n\nQuestion: {INPUT_TAG}\nAnswer:",
    "2wikimqa": f"Answer the question based on the given passages. Only give me the answer and do not output any other words.\n\nThe following are given passages.\n{CONTEXT_TAG}\n\nAnswer the question based on the given passages. Only give me the answer and do not output any other words.\n\nQuestion: {INPUT_TAG}\nAnswer:",
    "musique": f"Answer the question based on the given passages. Only give me the answer and do not output any other words.\n\nThe following are given passages.\n{CONTEXT_TAG}\n\nAnswer the question based on the given passages. Only give me the answer and do not output any other words.\n\nQuestion: {INPUT_TAG}\nAnswer:",
    "nq": f"Answer the question based on the given documents. Only give me the answer and do not output any other words.\n\nThe following are given documents.\n{CONTEXT_TAG}\n\nAnswer the question based on the given documents. Only give me the answer and do not output any other words.\n\nQuestion: {INPUT_TAG}\nAnswer:",
    "popqa": f"Answer the question based on the given documents. Only give me the answer and do not output any other words.\n\nThe following are given documents.\n{CONTEXT_TAG}\n\nAnswer the question based on the given documents. Only give me the answer and do not output any other words.\n\nQuestion: {INPUT_TAG}\nAnswer:",
    "trivia": f"Answer the question based on the given documents. Only give me the answer and do not output any other words.\n\nThe following are given documents.\n{CONTEXT_TAG}\n\nAnswer the question based on the given documents. Only give me the answer and do not output any other words.\n\nQuestion: {INPUT_TAG}\nAnswer:",
    "multi_news": f"You are given several news passages. Write a one-page summary of all news. \n\nNews:\n{CONTEXT_TAG}\n\nNow, write a one-page summary of all the news.\n\nSummary:",
    "gov_report": f"You are given a report by a government agency. Write a one-page summary of the report.\n\nReport:\n{CONTEXT_TAG}\n\nNow, write a one-page summary of the report.\n\nSummary:",
    "billsum": f"Please summarize the following bills:\n{CONTEXT_TAG}\n\nNow, write a summary of all the bills.\n\nSummary:",
    "trec_fine": f"Use the provided mapping from the text to label to assign a label to the text. Only output \"label: {{label}}\" and nothing else. All labels are: manner of an action, inventions, books and other creative pieces, animals, expression abbreviated, an individual, a group or organization of persons, title of a person, definition of something, dates, reasons, events, states, description of something, number of something, other entities, letters like a-z, other locations, religions, food, countries, colors, equivalent terms, cities, organs of body, diseases and medicine, mountains, prices, products, the lasting time of something, elements and substances, sports, plants, techniques and methods, size, area and volume, description of a person, musical instrument, abbreviation, other numbers, speed, words with a special property, languages, fractions, postcodes or other codes, linear measures, temperature, symbols and signs, ranks, vehicles, weight, currency names.\n\n{CONTEXT_TAG}\n{INPUT_TAG}\nlabel:",
    "banking77": f"Use the provided mapping from the text to label to assign a label to the text. Only output \"label: {{label}}\" and nothing else. All labels are: activate_my_card, age_limit, apple_pay_or_google_pay, atm_support, automatic_top_up, balance_not_updated_after_bank_transfer, balance_not_updated_after_cheque_or_cash_deposit, beneficiary_not_allowed, cancel_transfer, card_about_to_expire, card_acceptance, card_arrival, card_delivery_estimate, card_linking, card_not_working, card_payment_fee_charged, card_payment_not_recognised, card_payment_wrong_exchange_rate, card_swallowed, cash_withdrawal_charge, cash_withdrawal_not_recognised, change_pin, compromised_card, contactless_not_working, country_support, declined_card_payment, declined_cash_withdrawal, declined_transfer, direct_debit_payment_not_recognised, disposable_card_limits, edit_personal_details, exchange_charge, exchange_rate, exchange_via_app, extra_charge_on_statement, failed_transfer, fiat_currency_support, get_disposable_virtual_card, get_physical_card, getting_spare_card, getting_virtual_card, lost_or_stolen_card, lost_or_stolen_phone, order_physical_card, passcode_forgotten, pending_card_payment, pending_cash_withdrawal, pending_top_up, pending_transfer, pin_blocked, receiving_money, Refund_not_showing_up, request_refund, reverted_card_payment?, supported_cards_and_currencies, terminate_account, top_up_by_bank_transfer_charge, top_up_by_card_charge, top_up_by_cash_or_cheque, top_up_failed, top_up_limits, top_up_reverted, topping_up_by_card, transaction_charged_twice, transfer_fee_charged, transfer_into_account, transfer_not_received_by_recipient, transfer_timing, unable_to_verify_identity, verify_my_identity, verify_source_of_funds, verify_top_up, virtual_card_not_working, visa_or_mastercard, why_verify_identity, wrong_amount_of_cash_received, wrong_exchange_rate_for_cash_withdrawal.\n\n{CONTEXT_TAG}\n{INPUT_TAG}\nlabel:",
    "clinc150": f"Use the provided mapping from the text to label to assign a label to the text. Only output \"label: {{label}}\" and nothing else. All labels are: restaurant_reviews, nutrition_info, account_blocked, oil_change_how, time, weather, redeem_rewards, interest_rate, gas_type, accept_reservations, smart_home, user_name, report_lost_card, repeat, whisper_mode, what_are_your_hobbies, order, jump_start, schedule_meeting, meeting_schedule, freeze_account, what_song, meaning_of_life, restaurant_reservation, traffic, make_call, text, bill_balance, improve_credit_score, change_language, no, measurement_conversion, timer, flip_coin, do_you_have_pets, balance, tell_joke, last_maintenance, exchange_rate, uber, car_rental, credit_limit, oos, shopping_list, expiration_date, routing, meal_suggestion, tire_change, todo_list, card_declined, rewards_balance, change_accent, vaccines, reminder_update, food_last, change_ai_name, bill_due, who_do_you_work_for, share_location, international_visa, calendar, translate, carry_on, book_flight, insurance_change, todo_list_update, timezone, cancel_reservation, transactions, credit_score, report_fraud, spending_history, directions, spelling, insurance, what_is_your_name, reminder, where_are_you_from, distance, payday, flight_status, find_phone, greeting, alarm, order_status, confirm_reservation, cook_time, damaged_card, reset_settings, pin_change, replacement_card_duration, new_card, roll_dice, income, taxes, date, who_made_you, pto_request, tire_pressure, how_old_are_you, rollover_401k, pto_request_status, how_busy, application_status, recipe, calendar_update, play_music, yes, direct_deposit, credit_limit_change, gas, pay_bill, ingredients_list, lost_luggage, goodbye, what_can_i_ask_you, book_hotel, are_you_a_bot, next_song, change_speed, plug_type, maybe, w2, oil_change_when, thank_you, shopping_list_update, pto_balance, order_checks, travel_alert, fun_fact, sync_device, schedule_maintenance, apr, transfer, ingredient_substitution, calories, current_location, international_fees, calculator, definition, next_holiday, update_playlist, mpg, min_payment, change_user_name, restaurant_suggestion, travel_notification, cancel, pto_used, travel_suggestion, change_volume.\n\n{CONTEXT_TAG}\n{INPUT_TAG}\nlabel:",
    "arc_easy": f"Answer the question based on the given documents. Only give me the answer and do not output any other words.\n\nThe following are given documents.\n{CONTEXT_TAG}\n\nQuestion: {INPUT_TAG}\nTherefore, among A through D or 1 through 4, the answer is",
    "arc_challenge": f"Answer the question based on the given documents. Only give me the answer and do not output any other words.\n\nThe following are given documents.\n{CONTEXT_TAG}\n\nQuestion: {INPUT_TAG}\nTherefore, among A through D or 1 through 4, the answer is",
    "piqa": f"Answer the question based on the given documents. Only give me the answer and do not output any other words.\n\n\The following are given documents.\n{CONTEXT_TAG}\n\nQuestion: {INPUT_TAG}\nTherefore, among A through B, the answer is",
    "social_i_qa": f"Answer the question based on the given documents. Only give me the answer and do not output any other words.\n\nThe following are given documents.\n{CONTEXT_TAG}\n\nQuestion: {INPUT_TAG}\nTherefore, among A through C, the answer is",
}

dataset2compression_instruction = {
    "hotpotqa": "Answer the question based on the given documents. Only give me the answer and do not output any other words.\n\nThe following are given documents.\n",
    "2wikimqa": "Answer the question based on the given documents. Only give me the answer and do not output any other words.\n\nThe following are given documents.\n",
    "musique": "Answer the question based on the given documents. Only give me the answer and do not output any other words.\n\nThe following are given documents.\n",
    "nq": "Answer the question based on the given documents. Only give me the answer and do not output any other words.\n\nThe following are given documents.\n",
    "popqa": "Answer the question based on the given documents. Only give me the answer and do not output any other words.\n\nThe following are given documents.\n",
    "trivia": "Answer the question based on the given documents. Only give me the answer and do not output any other words.\n\nThe following are given documents.\n",
    "multi_news": "Summarize the given documents.\n",
    "gov_report": "Summarize the given documents.\n",
    "billsum": "Summarize the given documents.\n",
    "trec_fine": "Compress the few-shot examples, retaining key patterns and diversity while removing redundancy.\n",
    "banking77": "Compress the few-shot examples, retaining key patterns and diversity while removing redundancy.\n",
    "clinc150": "Compress the few-shot examples, retaining key patterns and diversity while removing redundancy.\n",
    "arc_easy": "Compress the context to the core facts and relationships that are pivotal for solving the reasoning task.\n",
    "arc_challenge": "Compress the context to the core facts and relationships that are pivotal for solving the reasoning task.\n",
    "piqa": "Compress the context to the core facts and relationships that are pivotal for solving the reasoning task.\n",
    "social_i_qa": "Compress the context to the core facts and relationships that are pivotal for solving the reasoning task.\n",
}

dataset2maxlen = {
    "hotpotqa": 32,
    "2wikimqa": 32,
    "musique": 32,
    "nq": 128,
    "popqa": 128,
    "trivia": 128,
    "multi_news": 512,
    "gov_report": 512,
    "billsum": 512,
    "trec_fine": 64,
    "banking77": 64,
    "clinc150": 64,
    "arc_easy": 128,
    "arc_challenge": 128,
    "piqa": 128,
    "social_i_qa": 128,
}

dataset2metric = {
    "hotpotqa": ["qa_f1_score"],
    "2wikimqa": ["qa_f1_score"],
    "musique": ["qa_f1_score"],
    "nq": ["em_score"],
    "popqa": ["em_score"],
    "trivia": ["em_score"],
    "multi_news": ["rouge_score"],
    "gov_report": ["rouge_score"],
    "billsum": ["rouge_score"],
    "trec_fine": ["classification_score"],
    "banking77": ["classification_score"],
    "clinc150": ["classification_score"],
    "arc_easy": ["em_score"],
    "arc_challenge": ["em_score"],
    "piqa": ["em_score"],
    "social_i_qa": ["em_score"],
}
